knp_snappy:
    pdf:
        enabled:    true
        binary:     '%env(WKHTMLTOPDF_PATH2)%'
        options:
            lowquality: true
            margin-top: 10mm
            page-size: A4
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH2)%'
        options:    []
