framework:
    mailer:
        dsn: 'gmail+smtp://azizowski10@gmail.com:hklrkkxcywctrmdp@default'
        envelope:
            sender: 'azizowski10@gmail.com'
        headers:
            From: 'PathFinder <azizowski10@gmail.com>'
